name: 'Build Micro Services Docker image'
description: 'Build Rocket.Chat Micro Services Docker images'

inputs:
  docker-tag:
    required: true
  service:
    required: true
  username:
    required: false
  password:
    required: false

outputs:
  image-name:
    value: ${{ steps.build-image.outputs.image-name }}

runs:
  using: "composite"
  steps:
    # - shell: bash
    #   name: Free disk space
    #   run: |
    #     sudo swapoff -a
    #     sudo rm -f /swapfile
    #     sudo apt clean
    #     docker rmi $(docker image ls -aq)
    #     df -h

    - shell: bash
      id: build-image
      run: |
        LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")

        IMAGE_TAG="${{ inputs.docker-tag }}"

        IMAGE_NAME="ghcr.io/${LOWERCASE_REPOSITORY}/${{ inputs.service }}-service:${IMAGE_TAG}"

        echo "Building Docker image for service: ${{ inputs.service }}:${IMAGE_TAG}"

        if [[ "${{ inputs.service }}" == "ddp-streamer" ]]; then
          DOCKERFILE_PATH="./ee/apps/ddp-streamer/Dockerfile"
        else
          DOCKERFILE_PATH="./apps/meteor/ee/server/services/Dockerfile"
        fi

        docker build \
          --build-arg SERVICE=${{ inputs.service }} \
          -t ${IMAGE_NAME} \
          -f ${DOCKERFILE_PATH} \
          .

        echo "::set-output name=image-name::${IMAGE_NAME}"

    - name: Login to GitHub Container Registry
      if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'release' || github.ref == 'refs/heads/develop'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Publish image
      shell: bash
      if: github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'release' || github.ref == 'refs/heads/develop'
      run: |
        echo "Push Docker image: ${{ steps.build-image.outputs.image-name }}"

        docker push ${{ steps.build-image.outputs.image-name }}
